run:
  concurrency: 4
  deadline: 5m

linters-settings:
  cyclop:
    max-complexity: 11

linters:
  enable-all: true
  disable:
    - interfacer
    - gas
    - megacheck
    - structcheck
    - staticcheck
    - varnamelen
    - gochecknoglobals
    - scopelint
    - funlen
    - godox
    - exhaustivestruct
    - goerr113
    - wsl
    - nlreturn
    - gomnd
    - paralleltest
    - wrapcheck
    - testpackage
    - golint
    - maligned
    - gofumpt
    - forbidigo
    - exhaustruct
    - nonamedreturns
    - tagliatelle
    - gomoddirectives
    - ifshort
    - ireturn
    - nosnakecase
    - deadcode
    - varcheck
    # Disabled because they are add no value or result in false positives.
    - depguard
    - musttag

issues:
  max-same-issues: 0
