# Sets the default category used to report rules which don't specify one.
default-category: uncalled
rules:
  - name: sql-rows-err
    disabled: false
    category: sql
    packages:
      - database/sql
      - github.com/jmoiron/sqlx
    methods: []
    results:
      - type: .Rows
        pointer: true
        expect:
          call: .Err
          args: []
      - type: error
        pointer: false
  - name: http-response-body-close
    disabled: false
    category: http
    packages:
      - net/http
    methods: []
    results:
      - type: .Response
        pointer: true
        expect:
          call: .Body.Close
          args: []
      - type: error
        pointer: false

