# Sets the default category used to report rules which don't specify one.
default-category: uncalled
rules:
  # Check for missing sql Rows.Err() calls.
  - name: sql-rows-err
    disabled: false
    category: sql
    packages:
      - database/sql
      - github.com/jmoiron/sqlx
    methods: []
    results:
      - type: .Rows
        pointer: true
        expect:
          call: .Err
          args: []
      - type: error
        pointer: false
  # Check for missing http Response.Body.Close() calls.
  - name: http-response-body-close
    disabled: false
    category: http
    packages:
      - net/http
    methods: []
    results:
      - type: .Response
        pointer: true
        expect:
          call: .Body.Close
          args: []
      - type: error
        pointer: false
  # Check for missing context CancelFunc() calls.
  - name: context-cancel
    disabled: false
    category: context
    packages:
      - context
    methods: []
    results:
      - type: .Context
        pointer: false
      - type: .CancelFunc
        pointer: false
        expect:
          call:
          args: []

