rules:
  - name: sql.Rows.Err
    disabled: false
    severity: warning
    packages:
      - database/sql
      - github.com/jmoiron/sqlx
    call:
      methods: []
      results:
        - type: .Rows
          pointer: true
        - type: error
          pointer: false
    expect:
      method: .Err
      result-index: 0
      args: []
  - name: http.Response.Body.Close
    disabled: false
    severity: warning
    packages:
      - net/http
    call:
      methods: []
      results:
        - type: .Response
          pointer: true
        - type: error
          pointer: false
    expect:
      method: .Body.Close
      result-index: 0
      args: []
